code: Finishing UpdateHedgeDoc pipeline

diff --git a/UpdateHedgeDoc/Jenkinsfile b/UpdateHedgeDoc/Jenkinsfile
--- a/UpdateHedgeDoc/Jenkinsfile
+++ b/UpdateHedgeDoc/Jenkinsfile
@@ -1,1 +1,58 @@
-dummy
+pipeline {
+    agent any
+
+    environment {
+        COMPOSE_FILE = 'UpdateHedgeDoc/files/docker-compose.yml'
+        REGISTRY_API = 'https://quay.io/api/v1/repository/hedgedoc/hedgedoc/tag/'
+    }
+
+    stages {
+        stage('Check New Image') {
+            steps {
+                script {
+                    def currentTag = sh(script: "grep -oP 'quay.io/hedgedoc/hedgedoc:\\K[a-zA-Z0-9.-]+-alpine' ${COMPOSE_FILE}", returnStdout: true).trim()
+                    echo "Current Tag in docker-compose: ${currentTag}"
+                    def latestTagCmd = """
+                        curl -s "${REGISTRY_API}?limit=100" | \
+                        jq -r '.tags[] | select(.name | endswith("-alpine")) | .name' | head -n 1
+                    """
+                    def latestTag = sh(script: latestTagCmd, returnStdout: true).trim()
+                    echo "Last tag available in Quay.io: ${latestTag}"
+                    if (latestTag == "") {
+                        error "Can't get last tag in Quay.io"
+                    }
+                    if (currentTag != latestTag) {
+                        echo "New version Available! Updating from ${currentTag} to ${latestTag}."
+                        env.NEW_TAG_FOUND = 'true'
+                        env.LATEST_TAG = latestTag
+                        env.CURRENT_TAG = currentTag
+                    } else {
+                        echo "Container in last version: ${currentTag}."
+                        env.NEW_TAG_FOUND = 'false'
+                    }
+                }
+            }
+        }
+
+        stage('Deploy Update') {
+            when {
+                environment name: 'NEW_TAG_FOUND', value: 'true'
+            }
+            steps {
+                dir('UpdateHedgeDoc/files') {
+                    script {
+                        sh "sed -i 's/${env.CURRENT_TAG}/${env.LATEST_TAG}/g' docker-compose.yml"
+                        echo "Stopping current service..."
+                        sh "docker compose stop"
+                        echo "Deleting container..."
+                        sh "docker compose rm -f"
+                        echo "Deleting image to save space..."
+                        sh "docker rmi quay.io/hedgedoc/hedgedoc:${env.CURRENT_TAG} || true"
+                        echo "Deploying new version..."
+                        sh "docker compose up -d"
+                    }
+                }
+            }
+        }
+    }
+}
